//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseCommon.Common.Report {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaseCommon.Common.Report.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;License&gt;
        ///&lt;Data&gt;
        ///&lt;LicensedTo&gt;The World Bank&lt;/LicensedTo&gt;
        ///&lt;EmailTo&gt;kkumar3@worldbankgroup.org&lt;/EmailTo&gt;
        ///&lt;LicenseType&gt;Developer Small Business&lt;/LicenseType&gt;
        ///&lt;LicenseNote&gt;1 Developer And 1 Deployment Location&lt;/LicenseNote&gt;
        ///&lt;OrderID&gt;210316185957&lt;/OrderID&gt;
        ///&lt;UserID&gt;744916&lt;/UserID&gt;
        ///&lt;OEM&gt;This is not a redistributable license&lt;/OEM&gt;
        ///&lt;Products&gt;
        ///&lt;Product&gt;Aspose.Total for .NET&lt;/Product&gt;
        ///&lt;/Products&gt;
        ///&lt;EditionType&gt;Professional&lt;/EditionType&gt;
        ///&lt;SerialNumber&gt;03fb199a-5c8a-48db-992e-d084ff066d0c&lt;/SerialNumber&gt;
        ///&lt;Su [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LicenseAspose {
            get {
                return ResourceManager.GetString("LicenseAspose", resourceCulture);
            }
        }
    }
}
